# Ancilary Use Cases for VPEM and Cybersecurity Risk Management
 
There is significant value in using Neo4j for Vulnerability Prioritization and Exposure Management (VPEM) beyond the core use case of identifying internet-exposed vulnerabilities. Below are some additional queries and analyses that can be performed with vulnerability and KVE data.

In [27]:
from dotenv import load_dotenv
import os
from neo4j import GraphDatabase

load_dotenv()

# Connection details
URI = os.getenv("NEO4J_URI", "bolt://localhost:7687")
AUTH = (os.getenv("NEO4J_USER", "neo4j"), os.getenv("NEO4J_PASSWORD", "password"))
DB = os.getenv("NEO4J_DB", "nvd")

# A helper method to run Cypher queries
def run_cypher(query, parameters=None):
    driver = GraphDatabase.driver(URI, auth=AUTH)
    try:
        with driver.session(database=DB) as session:
            result = session.run(query, parameters or {})
            # .data() converts the stream into a list of dictionaries
            return result.data() 
    finally:
        driver.close()

### The "Immediate Action" Overlap

This query identifies vulnerabilities that have both a Critical/High CVSS score and are Known to be Exploited in the wild. This represents the "top of the funnel" for any security program.

**Why it matters**: CISA KEV is a "source of truth" for what attackers are actually doing. If a CVE is in this list, the probability of an attack is near 100%.

In [28]:
import pandas as pd

query = """
MATCH (v:CVE)-[:LISTED_IN]->(cat:Catalog {name: 'CISA KEV'})
WHERE v.baseScore >= 7.0 
  AND date(v.kev_addedDate) >= date() - duration('P90D') 
RETURN v.id AS CVE, 
       v.baseScore AS Severity, 
       v.kev_addedDate AS Date_Added_to_KEV,
       v.kev_dueDate AS Remediation_Deadline,
       v.description AS Summary
ORDER BY v.kev_addedDate DESC
"""
results = run_cypher(query)
# Print the results as an html table
df = pd.DataFrame(results)
df

,CVE,Severity,Date_Added_to_KEV,Remediation_Deadline,Summary
0,CVE-2025-14847,7.5,2025-12-29,2026-01-19,Mismatched length fields in Zlib compressed pr...
1,CVE-2023-52163,8.8,2025-12-22,2026-01-12,Digiever DS-2105 Pro 3.1.0.71-11 devices allow...
2,CVE-2025-20393,10.0,2025-12-17,2025-12-24,Cisco is aware of a potential vulnerability.&n...
3,CVE-2025-59718,9.1,2025-12-16,2025-12-23,A improper verification of cryptographic signa...
4,CVE-2025-43529,8.8,2025-12-15,2026-01-05,A use-after-free issue was addressed with impr...
5,CVE-2025-14174,8.8,2025-12-12,2026-01-02,Out of bounds memory access in ANGLE in Google...
6,CVE-2018-4063,8.8,2025-12-12,2026-01-02,An exploitable remote code execution vulnerabi...
7,CVE-2025-58360,8.2,2025-12-11,2026-01-01,GeoServer is an open source server that allows...
8,CVE-2025-6218,7.8,2025-12-09,2025-12-30,RARLAB WinRAR Directory Traversal Remote Code ...
9,CVE-2025-62221,7.8,2025-12-09,2025-12-30,None
10,CVE-2022-37055,9.8,2025-12-08,2025-12-29,D-Link Go-RT-AC750 GORTAC750_revA_v101b03 and ...
11,CVE-2025-66644,7.2,2025-12-08,2025-12-29,Array Networks ArrayOS AG before 9.4.5.9 allow...
12,CVE-2025-55182,10.0,2025-12-05,2025-12-12,A pre-authentication remote code execution vul...
13,CVE-2021-26828,8.8,2025-12-03,2025-12-24,OpenPLC ScadaBR through 0.9.1 on Linux and thr...
14,CVE-2025-48572,7.8,2025-12-02,2025-12-23,"In multiple locations, there is a possible way..."
15,CVE-2025-61757,9.8,2025-11-21,2025-12-12,None
16,CVE-2025-13223,8.8,2025-11-19,2025-12-10,Type Confusion in V8 in Google Chrome prior to...
17,CVE-2025-64446,9.4,2025-11-14,2025-11-21,A relative path traversal vulnerability in For...
18,CVE-2025-62215,7.0,2025-11-12,2025-12-03,None
19,CVE-2025-12480,9.1,2025-11-12,2025-12-03,"Triofox versions prior to 16.7.10368.56560, ar..."
20,CVE-2025-21042,8.8,2025-11-10,2025-12-01,Out-of-bounds write in libimagecodec.quram.so ...
21,CVE-2025-11371,7.5,2025-11-04,2025-11-25,In the default installation and configuration ...
22,CVE-2025-48703,9.0,2025-11-04,2025-11-25,CWP (aka Control Web Panel or CentOS Web Panel...
23,CVE-2025-24893,9.8,2025-10-30,2025-11-20,XWiki Platform is a generic wiki platform offe...
24,CVE-2025-41244,7.8,2025-10-30,2025-11-20,VMware Aria Operations and VMware Tools contai...
25,CVE-2025-6204,8.0,2025-10-28,2025-11-18,An Improper Control of Generation of Code (Cod...
26,CVE-2025-6205,9.1,2025-10-28,2025-11-18,A missing authorization vulnerability affectin...
27,CVE-2025-54236,9.1,2025-10-24,2025-11-14,"Adobe Commerce versions 2.4.9-alpha2, 2.4.8-p2..."
28,CVE-2025-59287,9.8,2025-10-24,2025-11-14,None
29,CVE-2025-61932,9.8,2025-10-22,2025-11-12,Lanscope Endpoint Manager (On-Premises) (Clien...
30,CVE-2022-48503,8.8,2025-10-20,2025-11-10,The issue was addressed with improved bounds c...
31,CVE-2025-2746,9.8,2025-10-20,2025-11-10,An authentication bypass vulnerability in Kent...
32,CVE-2025-2747,9.8,2025-10-20,2025-11-10,An authentication bypass vulnerability in Kent...
33,CVE-2025-61884,7.5,2025-10-20,2025-11-10,None
34,CVE-2025-33073,8.8,2025-10-20,2025-11-10,None
35,CVE-2025-54253,10.0,2025-10-15,2025-11-05,Adobe Experience Manager versions 6.5.23 and e...
36,CVE-2025-24990,7.8,2025-10-14,2025-11-04,None
37,CVE-2025-59230,7.8,2025-10-14,2025-11-04,None
38,CVE-2016-7836,9.8,2025-10-14,2025-11-04,SKYSEA Client View Ver.11.221.03 and earlier a...
39,CVE-2021-43798,7.5,2025-10-09,2025-10-30,Grafana is an open-source platform for monitor...
40,CVE-2013-3918,8.8,2025-10-06,2025-10-27,The InformationCardSigninHelper Class ActiveX ...
41,CVE-2025-61882,9.8,2025-10-06,2025-10-27,None
42,CVE-2010-3962,8.1,2025-10-06,2025-10-27,Use-after-free vulnerability in Microsoft Inte...
43,CVE-2010-3765,9.8,2025-10-06,2025-10-27,Mozilla Firefox 3.5.x through 3.5.14 and 3.6.x...
44,CVE-2021-43226,7.8,2025-10-06,2025-10-27,None
45,CVE-2021-22555,8.3,2025-10-06,2025-10-27,A heap out-of-bounds write affecting Linux sin...
46,CVE-2011-3402,8.8,2025-10-06,2025-10-27,Unspecified vulnerability in the TrueType font...

### Weakness Analysis (the CWE "Root Cause")

This query identifies which Common Weakness Enumerations (CWEs) are most frequently associated with exploited vulnerabilities. This helps you tell developers what coding patterns to stop using.

**Why it matters**: If "CWE-78: OS Command Injection" shows up as your #1 exploited weakness, you should prioritize a security training session or a linting rule specifically for that issue.

In [29]:
query = """
MATCH (w:CWE)<-[:HAS_PROBLEM_TYPE]-(v:CVE)-[:LISTED_IN]->(:Catalog {name: 'CISA KEV'})
RETURN w.id AS Weakness, 
       count(v) AS Exploited_CVE_Count
ORDER BY Exploited_CVE_Count DESC
LIMIT 10
"""
results = run_cypher(query)
# Print the results as an html table
df = pd.DataFrame(results)
df

  Weakness  Exploited_CVE_Count
0   CWE-78                   36
1  CWE-502                   26
2  CWE-416                   24
3   CWE-20                   21
4   CWE-22                   20
5   CWE-94                   18
6  CWE-306                   14
7  CWE-284                   14
8  CWE-122                   14
9  CWE-288                   12

### Vendor & Product Risk Concentration

Which vendors or products in your environment are "frequent flyers" in the KEV catalog ? This helps with **Vendor Risk Management** and **Supply Chain Security**.

**Why it matters**: This identifies "high-maintenance" products. If a specific VPN or Gateway product consistently appears in the KEV, it might be time to look for a more secure alternative.

In [30]:
query = """
MATCH (vend:Vendor)-[:PROVIDES]->(p:Product)<-[:AFFECTS]-(v:CVE)-[:LISTED_IN]->(:Catalog {name: 'CISA KEV'})
RETURN vend.name AS Vendor, 
       p.name AS Product, 
       count(DISTINCT v) AS KEV_Count
ORDER BY KEV_Count DESC
LIMIT 10
"""
results = run_cypher(query)
# Print the results as an html table
df = pd.DataFrame(results)
df

      Vendor                                         Product  KEV_Count
0  Microsoft                             Windows Server 2019        115
1  Microsoft                         Windows 10 Version 1809        108
2  Microsoft  Windows Server 2019 (Server Core installation)        107
3  Microsoft                             Windows Server 2016        105
4  Microsoft                             Windows Server 2022         94
5  Microsoft  Windows Server 2016 (Server Core installation)         93
6  Microsoft                         Windows 10 Version 1607         93
7  Microsoft                          Windows Server 2012 R2         89
8  Microsoft                         Windows 10 Version 1507         88
9  Microsoft                         Windows 10 Version 21H2         87

### The "Drop Everything" List: Recent Exploits on Live Assets

This query specifically looks for CVEs added to the KEV in the last 365 days that are currently running in your production environment on internet-facing instances.

This query is the "gold standard" for Exposure Management: It is the most valuable report a security team can receive:

- **Zeroing in on "Active Fire"**: A vulnerability scan might show 5,000 "Critical" bugs. This query likely narrows that down to 5 or 10. These are not theoretical risks; they are vulnerabilities that are currently being used by attackers and are sitting on your "front door" (public-facing servers).

- **Contextual Urgency**: By filtering for kev_addedDate within the last 90 days, you are focusing on the Exploitability Gap. This is the window between an exploit becoming public and an organization completing its patch cycle.

- **Direct Accountability**: Unlike a generic threat report, this provides the app.name and Instance_Name. You aren't just telling the team "Log4j is bad"; you are telling them "The Customer-Portal-API is currently vulnerable to an active exploit on server-prod-01."

In [31]:
query = """
MATCH (v:CVE)-[:LISTED_IN]->(cat:Catalog {name: 'CISA KEV'})
MATCH (v)-[:IDENTIFIED_IN]->(l:Library)-[:DEPENDENCY_OF]->(ba:BuildArtifact)-[:RUNNING_AS]->(app:Application)-[:HOSTED_ON]->(ins:ComputeInstance)

// Filter for internet reachability
WHERE ins.public_ip IS NOT NULL 
// Filter for recent KEV additions (365 days)
  AND date(v.kev_addedDate) >= date() - duration('P365D')

RETURN v.id AS Recent_CVE, 
       v.kev_addedDate AS KEV_Date, 
       app.name AS Affected_App, 
       ins.name AS Exposed_Instance, 
       ins.public_ip AS IP_Address
ORDER BY v.kev_addedDate DESC
"""
results = run_cypher(query)
# Print the results as an html table
df = pd.DataFrame(results)
df

       Recent_CVE    KEV_Date       Affected_App Exposed_Instance  IP_Address
0  CVE-2023-52163  2025-12-22  EdgeAuthenticator     edge-auth-01  52.14.99.1
1  CVE-2025-24990  2025-10-14  EdgeAuthenticator     edge-auth-01  52.14.99.1